{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "Authors",
        "Service": "/MyApplication/Services/service1.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "Name": "#Control:Name/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/MyApplication/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/MyApplication/Actions/UpdateEntityFailureMessage.action"
}