{
    "CreateLinks": [],
    "OnFailure": "/MyApplication/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/MyApplication/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "Name": "#Control:Name/#Value"
    },
    "Target": {
        "EntitySet": "Authors",
        "Service": "/MyApplication/Services/service1.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}